export const GET_APARTAMENTS = 'GET_APARTAMENTS';
export const GET_APARTAMENTS_SUCCESS = 'GET_APARTAMENTS_SUCCESS';
export const SET_LIKE = 'SET_LIKE';
export const SET_LIKE_SUCCESS = 'SET_LIKE_SUCCESS';